### ISSUE TITLE
Creating a Local HTTP Webserver with Python

### ISSUE THREAD

**Issue by Foogle7** [Foogle7/git_sandbox#3]
# **Local HTTP Webserver with Python**
1. Open command prompt on PC
2. Navigate to the folder you want using "cd (path)" more info [here](https://www.digitalcitizen.life/command-prompt-how-use-basic-commands)
3. Type "python -m http.server 8000" (with python 3 installed) 
4. Open browser and go to "http://localhost:8000/" 
![image](https://user-images.githubusercontent.com/69803093/90581618-adc77f80-e199-11ea-95a0-3ae31adc0cc0.png)

5. to stop press "Ctrl + C" while inside the command prompt

![image](https://user-images.githubusercontent.com/69803093/90581557-8f618400-e199-11ea-82a5-89428e525762.png)

**Comment by codemk8** [comment]
Good job! This is one of the simplest ways to serve a static folder on the network. You should remember the command :-)

However, this method does not render the index.html file (Please confirm) for you. Usually "index.html" at the root of your current directly is treated specially: it is used to render the homepage. But you can see that the page only shows "Directory listing for /".

You'll probably need to use some other packages and write some python code (google "python flask"). If you are interested you can test it out.

Anyway, good starting point!
